export const TicketStatus = {
    IN_PROGRESS: "IN_PROGRESS",
    CLOSED: "CLOSED",
} as const;

export const TicketPriority = {
    LOW: "LOW",
    MEDIUM: "MEDIUM",
    HIGH: "HIGH",
} as const;

export const TicketPermission = {
    CREATE_TICKET: "CREATE_TICKET",
    VIEW_OWN_TICKETS: "VIEW_OWN_TICKETS",
    UPDATE_TICKET_DESCRIPTION: "UPDATE_TICKET_DESCRIPTION",
    CLOSE_TICKET: "CLOSE_TICKET",
    VIEW_ASSIGNED_TICKETS: "VIEW_ASSIGNED_TICKETS",
    UPDATE_TICKET_STATUS: "UPDATE_TICKET_STATUS",
    UPDATE_TICKET_PRIORITY: "UPDATE_TICKET_PRIORITY",
    REASSIGN_TICKET: "REASSIGN_TICKET",
} as const;